export const HANEPBUHAY_AUTH_START = 'HANEPBUHAY_AUTH_START';
export const HANEPBUHAY_AUTH_SUCCESS = 'HANEPBUHAY_AUTH_SUCCESS';
export const HANEPBUHAY_AUTH_FAILED = 'HANEPBUHAY_AUTH_FAILED';

export const HANEPBUHAY_AUTH_LOGOUT = 'HANEPBUHAY_AUTH_LOGOUT';

export const FETCH_TRANSACTIONS_START = 'FETCH_TRANSACTIONS_START';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAILED = 'FETCH_TRANSACTIONS_FAILED';

export const FILTER_TRANSACTIONS_START = 'FILTER_TRANSACTIONS_START';
export const FILTER_TRANSACTIONS_SUCCESS = 'FILTER_TRANSACTIONS_SUCCESS';
export const FILTER_TRANSACTIONS_FAILED = 'FILTER_TRANSACTIONS_FAILED';

export const FETCH_TRANSACTION_START = 'FETCH_TRANSACTION_START';
export const FETCH_TRANSACTION_SUCCESS = 'FETCH_TRANSACTION_SUCCESS';
export const FETCH_TRANSACTION_FAILED = 'FETCH_TRANSACTION_FAILED';

export const FETCH_REJECT_REMARKS_START = 'FETCH_REJECT_REMARKS_START';
export const FETCH_REJECT_REMARKS_SUCCESS = 'FETCH_REJECT_REMARKS_SUCCESS';
export const FETCH_REJECT_REMARKS_FAILED = 'FETCH_REJECT_REMARKS_FAILED';

export const APPROVE_ID_START = 'APPROVE_ID_START';
export const APPROVE_ID_SUCCESS = 'APPROVE_ID_SUCCESS';
export const APPROVE_ID_FAILED = 'APPROVE_ID_FAILED ';

export const REJECT_ID_START = 'REJECT_ID_START';
export const REJECT_ID_SUCCESS = 'REJECT_ID_SUCCESS';
export const REJECT_ID_FAILED = 'REJECT_ID_FAILED';

export const SEARCH_ENTRIES_START = 'SEARCH_ENTRIES_START';
export const SEARCH_ENTRIES_SUCCESS = 'SEARCH_ENTRIES_SUCCESS';
export const SEARCH_ENTRIES_FAILED = 'SEARCH_ENTRIES_FAILED';

export const FILTER_DATAS_START = 'FILTER_DATAS_START';
export const FILTER_DATAS_SUCCESS = 'FILTER_DATAS_SUCCESS';
export const FILTER_DATAS_FAILED = 'FILTER_DATAS_FAILED';

export const DISCARD_TRANSACTION_START = 'DISCARD_TRANSACTION_START';
export const DISCARD_TRANSACTION_SUCCESS = 'DISCARD_TRANSACTION_SUCCESS';
export const DISCARD_TRANSACTION_FAILED = 'DISCARD_TRANSACTION_FAILED';

export const EDIT_TRANSACTION_START = 'EDIT_TRANSACTION_START';
export const EDIT_TRANSACTION_SUCCESS = 'EDIT_TRANSACTION_SUCCESS';
export const EDIT_TRANSACTION_FAILED = 'EDIT_TRANSACTION_FAILED';

export const FRAUD_DETECT_START = 'FRAUD_DETECT_START';
export const FRAUD_DETECT_SUCCESS = 'FRAUD_DETECT_SUCCESS';
export const FRAUD_DETECT_FAILED = 'FRAUD_DETECT_FAILED';

export const FETCH_TUPAD_START = 'FETCH_TUPAD_START';
export const FETCH_TUPAD_SUCCESS = 'FETCH_TUPAD_SUCCESS';
export const FETCH_TUPAD_FAILED = 'FETCH_TUPAD_FAILED';

export const SAVE_TUPAD_START = 'SAVE_TUPAD_START';
export const SAVE_TUPAD_SUCCESS = 'SAVE_TUPAD_SUCCESS';
export const SAVE_TUPAD_FAILED = 'SAVE_TUPAD_FAILED';
